#!/bin/bash

if [ -f "$1" ]; then
    if [ -e "${1%.docx}-media" ]; then
	rm -rf "${1%.docx}-media"
    fi
    mkdir "${1%.docx}-media"
    pandoc -s -f docx -t markdown "$1" -o "${1%.docx}.md" --extract-media="${1%.docx}-media"
else
    echo "File $1 does not exist."
fi
